name: Production Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Install kubectl
      uses: azure/setup-kubectl@v4
    - name: Install Helm
      uses: azure/setup-helm@v4

    - name: Configure kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    - name: Build image
      run: |
        IMAGE_ID=$(openssl rand -hex 8)
        IMAGE=ttl.sh/${IMAGE_ID}-fact-app-prod:1h

        docker build -f cicd/docker/Dockerfile -t $IMAGE .
        docker push $IMAGE

        echo "IMAGE=$IMAGE" >> $GITHUB_ENV

    - name: Deploy
      run: |
        helm upgrade --install \
        fact-app \
        cicd/helm \
        --values cicd/helm/environments/production.yaml \
        --namespace production \
        --create-namespace \
        --set image.repository=$IMAGE \
        --set env.VERSION=prod \
        --set env.COMMIT=${{ github.sha }}
